#!/usr/bin/env bash
# Alibaba Cloud ECS host-agent cleaner. Run as root.
set -u
export LC_ALL=C
VERSION=3.0.0
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
AGENT_RE='(AliYunDun(Monitor|Update)?|aegis|argusagent|cloudmonitor|aliyun-service|aliyun-assist|assist-daemon|loongcollector|ilogtail|logtaild)'
PROC_NAMES='^(AliYunDun|AliYunDunMonitor|AliYunDunUpdate|AliHips|aegis|argusagent|aliyun-service|assist-daemon|AssistDaemon|loongcollector|ilogtail|logtail|logtaild)$'
PROTECTED='^(cloud-init|systemd|sshd|lvm2-monitor|mdmonitor)(\.service)?$'
DIRS=(/usr/local/aegis /usr/local/cloudmonitor /usr/local/share/aliyun-assist /usr/local/share/assist-daemon /usr/local/aliyun-assist /usr/local/ilogtail /usr/local/loongcollector /opt/loongcollector /etc/ilogtail /etc/loongcollector /etc/cloudmonitor)
FILES=(/usr/sbin/aliyun-service /usr/sbin/aliyun_installer /usr/share/doc/aliyun-assist)
# NOTE: /run/systemd/system is included because it holds runtime-generated
# units (e.g. from SysV compat generators). It is scanned but treated as
# read-only/ephemeral: entries there are stopped/masked, not deleted, since
# they are regenerated by systemd itself from the on-disk unit files above.
UNIT_DIRS=(/etc/systemd/system /usr/lib/systemd/system /lib/systemd/system)
RUNTIME_UNIT_DIRS=(/run/systemd/system)
DIAG_LOG=/tmp/alibaba-agent-cleanup-diag.log
RESIDUALS=()
: > "$DIAG_LOG" 2>/dev/null || DIAG_LOG=/dev/null
have(){ command -v "$1" >/dev/null 2>&1; }
known_unit(){ [[ "${1,,}" =~ (aegis|aliyun|aliyundun|argus|cloudmonitor|assist-daemon|loongcollector|ilogtail|logtail) ]]; }
protected(){ [[ "$1" =~ $PROTECTED ]]; }
residual(){ RESIDUALS+=("$*"); }
diag(){ printf '%s\n' "$*" >> "$DIAG_LOG"; }
[[ $EUID -eq 0 ]] || { echo 'ERROR: run as root.' >&2; exit 1; }
have systemctl || { echo 'ERROR: systemctl is required.' >&2; exit 1; }
printf '\n============================================================\n Alibaba Cloud Agent Cleaner v%s\n============================================================\n' "$VERSION"
printf 'Only identified Alibaba Cloud agents are targeted. System services are protected.\nDiagnostic log: %s\n\n' "$DIAG_LOG"

# PID match requires an exact comm name or an executable/cmdline under fixed agent roots.
agent_pids(){
    local p pid comm exe cmd
    for p in /proc/[0-9]*; do
        [[ -d $p ]] || continue; pid=${p##*/}; IFS= read -r comm < "$p/comm" 2>/dev/null || comm=''
        if [[ $comm =~ $PROC_NAMES ]]; then printf '%s\n' "$pid"; continue; fi
        exe=$(readlink -f "$p/exe" 2>/dev/null || true); cmd=$(tr '\0' ' ' < "$p/cmdline" 2>/dev/null || true)
        case "$exe $cmd" in */usr/local/aegis/*|*/usr/local/cloudmonitor/*|*/usr/local/share/aliyun-assist/*|*/usr/local/share/assist-daemon/*|*/usr/local/aliyun-assist/*|*/usr/local/ilogtail/*|*/usr/local/loongcollector/*|*/opt/loongcollector/*) printf '%s\n' "$pid";; esac
    done
}

# Human-readable snapshot of one PID, for before/after respawn diagnosis.
pid_snapshot(){
    local pid=$1 line exe
    [[ -d /proc/$pid ]] || { echo "pid=$pid state=GONE"; return; }
    line=$(ps -o pid=,ppid=,stat=,etimes=,lstart= -p "$pid" 2>/dev/null | sed 's/^[[:space:]]*//')
    exe=$(readlink -f "/proc/$pid/exe" 2>/dev/null || echo '?')
    echo "pid=$pid [$line] exe=$exe"
}

# Freeze a set of PIDs with SIGSTOP before SIGKILL. A process that is stopped
# cannot execute its own signal handlers or watchdog loop, so it cannot
# fork()/exec() a replacement of a sibling that is killed in the same batch.
# This defeats the common "mutually-supervising trio" self-protection pattern
# (each agent process watches the other two and instantly relaunches them),
# which is why a plain `kill -9 pid1 pid2 pid3` alone is not reliable: the
# kernel does not guarantee the three SIGKILLs are observed atomically, and a
# process can still be scheduled to notice a sibling's death microseconds
# before its own signal is delivered.
freeze_and_kill(){
    local -a pids=("$@")
    [[ ${#pids[@]} -gt 0 ]] || return 0
    kill -STOP "${pids[@]}" 2>/dev/null || true
    sleep 0.3
    # While frozen, unlink the on-disk executables so that even if some
    # process outside this batch tries to fork/exec a replacement, exec()
    # fails (ENOENT). This does not affect the already-running (frozen)
    # processes, which keep their already-open inode.
    local pid exe
    for pid in "${pids[@]}"; do
        exe=$(readlink -f "/proc/$pid/exe" 2>/dev/null || true)
        if [[ -n $exe && $exe == /usr/local/aegis/* ]]; then
            chattr -i -a -- "$exe" 2>/dev/null || true
            rm -f -- "$exe" 2>/dev/null || true
        fi
    done
    kill -KILL "${pids[@]}" 2>/dev/null || true
}

# Robustly terminate agent processes, tolerating a respawn watchdog.
# Distinguishes "same PID survived SIGKILL" (kernel-level protection, cannot
# be fixed from userspace) from "a new PID appeared" (something else is
# relaunching it; each round re-discovers and re-freezes the new PID(s) too).
terminate_agent_processes(){
    local round=0 max_rounds=6
    local -a before after children
    while (( round < max_rounds )); do
        round=$((round+1))
        mapfile -t before < <(agent_pids | sort -un)
        if [[ ${#before[@]} -eq 0 ]]; then
            (( round == 1 )) && echo 'No matching agent processes were running.'
            return 0
        fi
        echo "  round $round: targeting PID(s): ${before[*]}"
        local pid
        for pid in "${before[@]}"; do diag "round $round before: $(pid_snapshot "$pid")"; done
        freeze_and_kill "${before[@]}"
        for pid in "${before[@]}"; do
            mapfile -t children < <(pgrep -P "$pid" 2>/dev/null || true)
            [[ ${#children[@]} -gt 0 ]] && freeze_and_kill "${children[@]}"
        done
        sleep 2
        mapfile -t after < <(agent_pids | sort -un)
        if [[ ${#after[@]} -eq 0 ]]; then
            echo "  round $round: all targeted processes are gone."
            return 0
        fi
        for pid in "${after[@]}"; do
            diag "round $round after: $(pid_snapshot "$pid")"
            if printf '%s\n' "${before[@]}" | grep -qx "$pid"; then
                echo "  round $round: WARNING - PID $pid is still the SAME PID after SIGKILL (see $DIAG_LOG)."
            else
                echo "  round $round: PID $pid is NEW (a supervisor relaunched the agent); retrying."
            fi
        done
    done
    return 1
}

printf '[1/9] Detecting Alibaba Cloud agents...\n'
for n in AliYunDun AliYunDunMonitor AliYunDunUpdate AliHips aegis argusagent aliyun-service; do p=$(pgrep -x "$n" 2>/dev/null || true); [[ -z $p ]] || echo "Detected $n PID(s): ${p//$'\n'/, }"; done
for d in "${DIRS[@]}"; do [[ ! -e $d ]] || echo "Detected $d"; done
systemctl show aegis.service -p LoadState --value 2>/dev/null | grep -qv '^not-found$' && echo 'Detected aegis.service'
have lsmod && lsmod 2>/dev/null | grep -qi aegis && echo 'Detected an aegis-related kernel module'
if have lsattr; then for d in "${DIRS[@]}"; do [[ -e $d ]] || continue; a=$(lsattr -d "$d" 2>/dev/null; lsattr -R "$d" 2>/dev/null | awk '$1 ~ /[ia]/ {print}' | head -20 || true); [[ -z $a ]] || printf 'Immutable/append-only entries under %s:\n%s\n' "$d" "$a"; done; fi

declare -A UNITS=()
find_related_units(){
    local d
    while read -r u _; do [[ -n ${u:-} ]] || continue; b=${u##*/}; known_unit "$b" && ! protected "$b" && UNITS[$u]=1; done < <(systemctl list-unit-files --no-legend --no-pager 2>/dev/null || true)
    for u in aegis.service aegis_update.service aliyun.service cloudmonitor.service aliyun-assist.service assist-daemon.service AssistDaemon.service loongcollector.service ilogtail.service logtaild.service; do s=$(systemctl show "$u" -p LoadState --value 2>/dev/null || true); [[ -z $s || $s == not-found ]] || UNITS[$u]=1; done
}
find_related_units
printf '[2/9] Stopping and masking services...\n'
# `disable` alone was observed to be insufficient: a live agent process can
# re-create its own enablement symlink. `mask` replaces the unit file with a
# symlink to /dev/null, which `systemctl start/enable` refuses to act on even
# if something re-invokes them, so it is applied before the kill step too.
for u in "${!UNITS[@]}"; do systemctl stop "$u" 2>/dev/null || true; systemctl disable "$u" 2>/dev/null || true; systemctl mask "$u" 2>/dev/null || true; done
# SysV-compatibility init scripts (systemd-sysv-generator turns these into
# transient units at boot even if no native unit file exists).
for s in /etc/init.d/aegis /etc/init.d/aegisd /etc/init.d/argusagent /etc/init.d/cloudmonitor; do
    [[ -x $s ]] || continue
    "$s" stop >/dev/null 2>&1 || true
    if have update-rc.d; then update-rc.d -f "${s##*/}" remove >/dev/null 2>&1 || true; fi
    if have chkconfig; then chkconfig "${s##*/}" off >/dev/null 2>&1 || true; fi
done

printf '[3/9] Running official uninstall procedures...\n'
if [[ -d /usr/local/aegis ]]; then
    official=''; for c in /usr/local/aegis/uninstall.sh /usr/local/aegis/aegis_client/uninstall.sh /usr/local/aegis/uninstall; do [[ -x $c ]] && official=$c && break; done
    if [[ -n $official ]]; then "$official" >/tmp/alibaba-aegis-uninstall.log 2>&1 || echo 'Official Aegis uninstaller reported failure (expected under self-protection); continuing.'
    elif have curl || have wget; then
        t=$(mktemp /tmp/alibaba-aegis-uninstall.XXXXXX) || t=''
        if [[ -n $t ]]; then
            if { have curl && curl -fsSL --max-time 20 https://update2.aegis.aliyun.com/download/uninstall.sh -o "$t"; } || { have wget && wget -q --timeout=20 https://update2.aegis.aliyun.com/download/uninstall.sh -O "$t"; }; then bash "$t" >/tmp/alibaba-aegis-uninstall.log 2>&1 || echo 'Official Aegis uninstaller reported failure (expected under self-protection); continuing.'; else echo 'Official Aegis uninstaller unavailable; continuing local cleanup.'; fi
            rm -f -- "$t"
        fi
    else echo 'curl/wget unavailable; skipped official uninstaller.'; fi
fi
if [[ -x /usr/local/cloudmonitor/cloudmonitorCtl.sh ]]; then /usr/local/cloudmonitor/cloudmonitorCtl.sh stop >/dev/null 2>&1 || true; /usr/local/cloudmonitor/cloudmonitorCtl.sh uninstall >/dev/null 2>&1 || true; fi

# NOTE: the official uninstaller's failure is explicitly NOT treated as
# success or failure here - only the final verification step decides that.

printf '[4/9] Terminating agent processes (this is the step that actually matters if self-protection is active)...\n'
if terminate_agent_processes; then
    proc_kill_ok=1
else
    proc_kill_ok=0
    echo '  Could not confirm all agent processes exited. Attribute/file removal will still be attempted, but is expected to be partially blocked while a process keeps re-asserting protection; see final verification.'
fi

printf '[5/9] Removing self-protection attributes (immutable/append-only)...\n'
# Done AFTER process termination, not before: if attributes are cleared while
# the agent is still alive, a live agent has been observed to re-assert
# chattr +i on its own files within seconds, which is why a later `rm -rf`
# fails with "Operation not permitted" even though this step reported success.
if have chattr; then
    for d in "${DIRS[@]}"; do [[ -e $d ]] && chattr -R -i -a -- "$d" 2>/dev/null || true; done
    for f in "${FILES[@]}"; do [[ -e $f ]] && chattr -i -a -- "$f" 2>/dev/null || true; done
else
    echo 'chattr unavailable; attributes may block removal.'
fi

printf '[6/9] Removing agent files...\n'
for d in "${DIRS[@]}"; do
    [[ -e $d || -L $d ]] || continue
    chattr -R -i -a -- "$d" 2>/dev/null || true
    rm -rf --one-file-system -- "$d" 2>/dev/null || echo "Could not completely remove $d (likely a process is still holding protection on it; see step 4)."
done
for f in "${FILES[@]}"; do [[ -e $f || -L $f ]] || continue; chattr -i -a -- "$f" 2>/dev/null || true; rm -f -- "$f" 2>/dev/null || echo "Could not remove $f"; done
# Remove only packages whose package names explicitly identify these agents.
# No wildcard package expressions are passed to apt/rpm/dnf/yum.
PKG_RE='^(aegis|aegis-client|aliyun-assist|aliyun-service|cloudmonitor|cloudmonitor-agent|ilogtail|loongcollector|logtail|logtaild)((:[^[:space:]]+)?)$'
if have dpkg-query && have apt-get; then
    while IFS= read -r pkg; do [[ $pkg =~ $PKG_RE ]] && DEBIAN_FRONTEND=noninteractive apt-get purge -y "$pkg" >/dev/null 2>&1 || true; done < <(dpkg-query -W -f='${binary:Package}\n' 2>/dev/null || true)
elif have rpm; then
    while IFS= read -r pkg; do [[ $pkg =~ $PKG_RE ]] && { if have dnf; then dnf remove -y "$pkg" >/dev/null 2>&1 || true; elif have yum; then yum remove -y "$pkg" >/dev/null 2>&1 || true; else rpm -e "$pkg" >/dev/null 2>&1 || true; fi; }; done < <(rpm -qa --qf '%{NAME}\n' 2>/dev/null || true)
fi

printf '[7/9] Cleaning systemd unit files, enablement symlinks, and cron...\n'
find_related_units
for u in "${!UNITS[@]}"; do systemctl stop "$u" 2>/dev/null || true; systemctl disable "$u" 2>/dev/null || true; systemctl mask "$u" 2>/dev/null || true; done
for d in "${UNIT_DIRS[@]}"; do
    [[ -d $d ]] || continue
    # Direct unit files/symlinks in the unit directory itself.
    while IFS= read -r -d '' f; do
        u=${f##*/}; b=${u%%.*}
        { known_unit "$u" || grep -Eiq "$AGENT_RE|/usr/local/aegis|/usr/local/cloudmonitor" "$f" 2>/dev/null; } || continue
        protected "$b" && continue
        systemctl stop "$u" 2>/dev/null || true; systemctl disable "$u" 2>/dev/null || true
        rm -f -- "$f" 2>/dev/null || true
    done < <(find "$d" -maxdepth 1 \( -type f -o -type l \) -print0 2>/dev/null)
    # Enablement symlinks can live under ANY *.wants or *.requires
    # subdirectory (not only multi-user.target.wants), so all of them are
    # scanned by symlink target, not just by name.
    while IFS= read -r -d '' link; do
        target=$(readlink -f "$link" 2>/dev/null || true)
        b=${link##*/}; tb=${target##*/}
        if { known_unit "$b" || known_unit "$tb"; } && ! protected "${tb%%.*}"; then
            rm -f -- "$link" 2>/dev/null || true
        fi
    done < <(find "$d" -mindepth 2 -maxdepth 3 -type l \( -path '*.wants/*' -o -path '*.requires/*' \) -print0 2>/dev/null)
done
systemctl daemon-reload 2>/dev/null || true; systemctl reset-failed 2>/dev/null || true
# rc.local can independently relaunch an agent even with systemd fully clean.
if [[ -f /etc/rc.local && ! -L /etc/rc.local ]] && grep -Eiq "$AGENT_RE|/usr/local/aegis|/usr/local/cloudmonitor" /etc/rc.local 2>/dev/null; then
    cp -p /etc/rc.local /etc/rc.local.pre-alibaba-cleanup.bak 2>/dev/null || true
    t=$(mktemp /etc/rc.local.clean.XXXXXX 2>/dev/null) || t=''
    if [[ -n $t ]]; then awk -v re="$AGENT_RE|/usr/local/aegis|/usr/local/cloudmonitor" 'tolower($0) !~ tolower(re)' /etc/rc.local > "$t" 2>/dev/null && cat "$t" > /etc/rc.local && rm -f "$t"; echo 'Removed Alibaba agent reference(s) from /etc/rc.local (backup saved).'; fi
fi
clean_cron(){
    local f=$1 t; [[ -f $f && ! -L $f ]] || return 0
    grep -Eiq "$AGENT_RE|/usr/local/aegis|/usr/local/cloudmonitor" "$f" || return 0
    t=$(mktemp "${f}.clean.XXXXXX") || return 1
    awk -v re="$AGENT_RE|/usr/local/aegis|/usr/local/cloudmonitor" 'tolower($0) !~ tolower(re)' "$f" > "$t" || { rm -f "$t"; return 1; }
    chown --reference="$f" "$t" 2>/dev/null || true; chmod --reference="$f" "$t" 2>/dev/null || true
    cat "$t" > "$f" || echo "Could not update cron file $f"; rm -f "$t"
}
for f in /etc/crontab /etc/cron.d/* /etc/cron.hourly/* /etc/cron.daily/* /etc/cron.weekly/* /etc/cron.monthly/* /var/spool/cron/* /var/spool/cron/crontabs/*; do [[ ! -e $f ]] || clean_cron "$f"; done

printf '[8/9] Re-checking for reappeared processes after file/unit removal...\n'
# A supervisor may only have been broken once its binary, unit, and
# enablement symlink were all gone. One more full termination pass, with the
# same freeze-then-kill/diagnose logic, catches that case instead of
# silently trusting step 4's result.
if terminate_agent_processes; then
    proc_kill_ok=1
else
    proc_kill_ok=0
fi

printf '[9/9] Final verification...\n'
for n in AliYunDun AliYunDunMonitor AliYunDunUpdate AliHips aegis argusagent aliyun-service; do
    p=$(pgrep -x "$n" 2>/dev/null || true)
    [[ -z $p ]] || residual "Process $n remains (PID(s): ${p//$'\n'/, }; see $DIAG_LOG for before/after PID diagnosis)"
done
p=$(agent_pids | sort -un); [[ -z $p ]] || residual "Agent path process remains (PID(s): ${p//$'\n'/, })"
for d in "${DIRS[@]}"; do [[ ! -e $d && ! -L $d ]] || residual "Directory remains: $d"; done
for f in "${FILES[@]}"; do [[ ! -e $f && ! -L $f ]] || residual "Agent file remains: $f"; done
while read -r u _; do
    [[ -n ${u:-} ]] || continue; b=${u##*/}
    known_unit "$b" || continue; protected "$b" && continue
    state=$(systemctl is-enabled "$u" 2>/dev/null || true)
    load=$(systemctl show "$u" -p LoadState --value 2>/dev/null || true)
    if [[ $load != not-found ]]; then residual "systemd unit file still loaded: $u (LoadState=$load, enabled state=$state)"; fi
done < <(systemctl list-unit-files --no-legend --no-pager 2>/dev/null || true)
while read -r u _; do
    [[ -n ${u:-} ]] || continue; b=${u##*/}
    known_unit "$b" && ! protected "$b" || continue
    astate=$(systemctl show "$u" -p ActiveState --value 2>/dev/null || true)
    [[ $astate != active && $astate != activating ]] || residual "Agent service is still running: $u ($astate)"
done < <(systemctl list-units --type=service --all --no-legend --no-pager 2>/dev/null || true)
for d in "${UNIT_DIRS[@]}" "${RUNTIME_UNIT_DIRS[@]}"; do
    [[ -d $d ]] || continue
    while IFS= read -r -d '' f; do
        u=${f##*/}; b=${u%%.*}
        if { known_unit "$u" || grep -Eiq "$AGENT_RE|/usr/local/aegis|/usr/local/cloudmonitor" "$f" 2>/dev/null; } && ! protected "$b"; then
            residual "systemd unit file remains: $f"
        fi
    done < <(find "$d" -maxdepth 3 \( -type f -o -type l \) -print0 2>/dev/null)
done
for f in /etc/crontab /etc/cron.d/* /etc/cron.hourly/* /etc/cron.daily/* /etc/cron.weekly/* /etc/cron.monthly/* /var/spool/cron/* /var/spool/cron/crontabs/*; do [[ -f $f ]] && grep -Eiq "$AGENT_RE|/usr/local/aegis|/usr/local/cloudmonitor" "$f" && residual "Cron entry remains in $f"; done
if [[ -f /etc/rc.local && ! -L /etc/rc.local ]] && grep -Eiq "$AGENT_RE|/usr/local/aegis|/usr/local/cloudmonitor" /etc/rc.local 2>/dev/null; then residual "Reference remains in /etc/rc.local"; fi
if have ss; then
    n=$(ss -ntup 2>/dev/null | grep -E '100\.100\.(88\.88|80\.184)' || true)
    [[ -z $n ]] || while IFS= read -r line; do residual "Network connection to Alibaba agent endpoint: $line"; done <<< "$n"
fi
have lsmod && lsmod 2>/dev/null | grep -qi aegis && residual "An aegis-related kernel module is still loaded (kernel-level self-protection; a reboot may be required, and the module should be prevented from auto-loading via /etc/modprobe.d before rebooting)"

if ((${#RESIDUALS[@]})); then
    printf '\n============================================================\n Alibaba Cloud Agent Cleanup: FAILED / RESIDUALS DETECTED\n============================================================\n'
    printf 'Residuals:\n'; printf ' - %s\n' "${RESIDUALS[@]}"
    printf '\nDiagnostic detail (PID/PPID/start-time before and after each kill attempt): %s\n' "$DIAG_LOG"
    if (( ! proc_kill_ok )); then
        printf 'At least one targeted process could not be confirmed terminated. If the SAME PID survived SIGKILL, this indicates protection below userspace (a kernel module or similar) that this script cannot safely override; consider disabling self-protection from the Aegis console before re-running, or rebooting and re-running immediately at boot before the agent restarts.\n'
    fi
    exit 1
fi
printf '\n============================================================\n Alibaba Cloud Agent Cleanup: SUCCESS\n============================================================\nAll checked processes, services, directories, systemd units, cron entries, rc.local references, and agent network connections are absent.\n'
